### PR TITLE
To be able to find boost.python better for boost(>=1.70)

### PR DESCRIPTION
**Pull request by xuning97**
After boost 1.70.0, use python directly is a possible choice, there is
no need to supply the version number of python

### CODE REVIEW

**Comment by AhmedSoliman** [comment]
I'm currently doing some major refactoring to our CMake files, I will review this once these land and you can rebase on top of them.

**Comment by xuning97** [comment]
sure

**Comment by AhmedSoliman** [comment]
Do you mind rebasing your diff on master now?

**Comment by xuning97** [comment]
> This needs rebasing.

hi, I've rebased the PR, may you have a look？

**Pull request closed without merging**
